crud_stack_tech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('salas_virtuais.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

salas_virtuais/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('criar_sala/', criar_sala, name='criar_sala'),
    path('editar_sala/<int:pk>/', editar_sala, name='editar_sala'),
    path('excluir_sala/<int:pk>/', excluir_sala, name='excluir_sala'),
]

salas_virtuais/models.py
from django.db import models

# Create your models here.

CATEGORIAS = (
    ('Programacao', 'Programação'),
    ('Design', 'Design'),
    ('Jogos_digitais', 'Jogos Digitais'),
    ('Mobile', 'Mobile'),
)

class Sala(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=255)
    categoria = models.CharField(choices=CATEGORIAS, max_length=100)
    limite_participantes = models.IntegerField(default=50)
    data_criacao = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nome

salas_virtuais/views.py
from django.shortcuts import render, redirect
from .models import Sala
from .models import CATEGORIAS
from datetime import datetime

# Create your views here.
def index(request):
    salas = Sala.objects.all().order_by('-data_criacao')
    context = {'salas': salas}
    return render(request, 'index.html', context)

def criar_sala(request):
    categorias = CATEGORIAS
    if request.method == 'POST':
        nome = request.POST.get('nome', None)
        descricao = request.POST.get('descricao', None)
        categoria = request.POST.get('categoria', None)
        limite_participantes = request.POST.get('limite', None)
        nova_sala = Sala(nome=nome, descricao=descricao, categoria=categoria,limite_participantes=limite_participantes)
        nova_sala.save()
        return redirect('/')
    context = {'categorias': categorias}
    return render(request, 'criar_sala.html', context)

def editar_sala(request, pk):
    sala = Sala.objects.get(id=pk)
    categorias = CATEGORIAS
    if request.method == 'POST':
        nome = request.POST.get('nome', None)
        descricao = request.POST.get('descricao', None)
        categoria = request.POST.get('categoria', None)
        limite_participantes = request.POST.get('limite', None)
        nova_sala = Sala(id=pk, nome=nome, descricao=descricao, categoria=categoria,limite_participantes=limite_participantes, data_criacao=datetime.now())
        nova_sala.save()
        return redirect('/')
    context = {'sala': sala, 'categorias': categorias}
    return render(request, 'editar_sala.html', context)

def excluir_sala(request, pk):
    sala = Sala.objects.get(id=pk)
    if request.method == 'POST':
        sala.delete()
        return redirect('/')
    context = {'sala': sala}
    return render(request, 'excluir_sala.html', context)

salas_virtuais/templates/criar_sala.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-3xl font-bold mb-3">Criar Sala</h1>

<form method="post">
    <label for="sala-nome">Nome:</label>
    <input type="text" name="sala-nome" id="sala-nome">
    <label for="sala-nome">Descrição:</label>
    <input type="text" name="sala-descricao" id="sala-descricao">
    <label for="sala-nome">Categoria:</label>
    <select name="sala-categoria" id="sala-categoria">
        <option selected disabled>---------</option>
    {% for categoria in categorias %}
        <option value="{{ categoria.0 }}">{{ categoria.1 }}</option>
    {% endfor %}
    </select>
    <label for="sala-nome" id="sala-limite">Limite:</label>
    <input type="number" name="sala-limite" id="sala-limite" value="1" min="1" max="99">

    <input type="submit" value="Criar">
</form>

{% endblock %}

salas_virtuais/templates/editar_sala.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-3xl font-bold mb-3">Editar Sala</h1>

<form method="post">
    {% csrf_token %}
    <label for="nome">Nome:</label>
    <input type="text" name="nome" id="nome" value="{{ sala.nome }}" required>
    <label for="nome">Descrição:</label>
    <input type="text" name="descricao" id="descricao" value="{{ sala.descricao }}" required>
    <label for="nome">Categoria:</label>
    <select name="categoria" id="categoria" required>
        <option selected disabled></option>
        {% for categoria in categorias %}
        <option value="{{ categoria.0 }}">{{ categoria.1 }}</option>
        {% endfor %}
    </select>
    <label for="nome" id="limite">Limite:</label>
    <input type="number" name="limite" id="limite" min="1" max="99" value="{{ sala.limite_participantes }}" required>

    <input type="submit" value="Criar">
</form>

<a href="{% url 'index' %}">Voltar</a>

{% endblock %}

salas_virtuais/templates/excluir_sala.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-3xl font-bold mb-3">Excluir Sala</h1>

<h3>Tem certeza que deseja excluir {{ sala.nome }}</h3>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Excluir">
</form>

<a href="{% url 'index' %}">Voltar</a>



{% endblock %}

salas_virtuais/templates/index.html
{% extends 'base.html' %}

{% block body %}
<h1 class="text-3xl font-bold mb-3">Bem-vindo</h1>
<a href="{% url 'criar_sala' %}">Criar Sala +</a>
<ul>
    {% for sala in salas %}
    <li>Nome da sala: {{ sala.nome }}</li>
    <li>Descrição: {{ sala.descricao }}</li>
    <li>Categoria: {{ sala.get_categoria_display }}</li>
    <li>Limite de participantes: {{ sala.limite_participantes }}</li>
    <li>Data de criação: {{ sala.data_criacao }}</li>
    <li><a href="{% url 'editar_sala' sala.id %}">Atualizar</a></li>
    <li><a href="{% url 'excluir_sala' sala.id %}">Deletar</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/teste.css' %}">
    {% block head %}

    {% endblock head %}
    {% block title %}{% endblock title %}
    <title>Salas de Aula Virtuais</title>
</head>
<body>
    <div class="m-10">
    {% block body %}

    {% endblock body %}
    </div>
</body>
</html>